export const ACTION_INCREMENT_LIKE = 'INCREMENT_LIKE';
export const ACTION_DECREMENT_LIKE = 'DECREMENT_LIKE';
export const ACTION_INCREMENT_BY_VALUE = 'INCREMENT_BY_VALUE';
export const ACTION_DECREMENT_BY_VALUE = 'DECREMENT_BY_VALUE';
export const ACTION_INCREMENT_DISLIKE = 'INCREMENT_DISLIKE';
export const ACTION_DECREMENT_DISLIKE = 'DECREMENT_DISLIKE';